remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
use_math: true
markdown: kramdown
kramdown:
  math_engine: katex
  syntax_highlighter: rouge
google_analytics:
theme: jekyll-theme-minimal